%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% This is for eliminating overlapped coordinates generated by pyFR
 %  coded by Ginn
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [non_overlapped_mat] = overlapped_coord_eliminator(overlapped_mat,indx_mat)
tempSize = length(unique(indx_mat));
non_overlapped_mat = zeros(tempSize,size(overlapped_mat,2));
% sort index matrix
% coord index is associated with coordinate location
% value index is associated with the value location on a certain location
[coord_indx,value_indx] = sort(indx_mat,'ascend');

% using recursive average method to average value with same coordinates
kkk = 1;
num = 1;
temp_value = overlapped_mat(value_indx(1),:);
for i = 2:length(coord_indx)
    if(coord_indx(i) == coord_indx(i-1))
        temp_value = temp_value + overlapped_mat(value_indx(i),:);
        num        = num + 1;
    else
        non_overlapped_mat(kkk,:) = temp_value./num;
        kkk = kkk+1;
        temp_value = overlapped_mat(value_indx(i),:);
        num        = 1;
    end
end
end